# Generated by Django 3.1.3 on 2020-11-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogin',
            name='Sid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
