# Generated by Django 3.1.3 on 2020-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcourse',
            name='ctitle',
            field=models.TextField(default='no title'),
        ),
    ]
