# Generated by Django 3.1.3 on 2020-11-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0002_tcourse_ctitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcourse',
            name='ctitle',
        ),
        migrations.AddField(
            model_name='tcourse',
            name='cname',
            field=models.TextField(default='no name'),
        ),
    ]
