# Generated by Django 3.1.3 on 2020-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0003_auto_20201124_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='mdocs',
            field=models.TextField(default=''),
        ),
    ]
