# Generated by Django 3.1.3 on 2020-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0004_auto_20201125_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='mdocs',
            field=models.TextField(null=True),
        ),
    ]
