# Generated by Django 3.1.3 on 2020-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0005_auto_20201128_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField(null=True)),
                ('present', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
