# Generated by Django 3.1.3 on 2020-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='tid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='cid',
            field=models.IntegerField(),
        ),
    ]
