# Generated by Django 3.1.3 on 2020-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0007_auto_20201202_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='stdattendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(default=-1)),
                ('cid', models.IntegerField()),
                ('tid', models.IntegerField(null=True)),
                ('present', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
