# Generated by Django 3.1.3 on 2020-12-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0008_auto_20201202_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stdattendance',
            new_name='attendance',
        ),
    ]
